### ISSUE TITLE
What's this setup.py of which you speak?

### ISSUE THREAD

**Issue by jofish** [ayman/flickrsavr#4]
In your readme you say

"Apply py3exiv2-mac.patch to setup.py.

You can cd into it and python3 setup.py install it from there."

It's not clear what setup.py you're referring to. There's not one if you unzip the master.zip, which is what I thought this would mean. And having followed the rest of the directions, I don't see one coming from anywhere else either.  Can you clarify a bit?

(Also, yay on making this work on python3. I was thinking it was probably time to go and convert it myself, as pyexiv2 just decided to stop working after some upgrade somewhere, but luckily you've already done it... Ta!)

**Comment by ayman** [comment]
Seems my old mac has some cached build stuff...V2 coming soon...removes all that weirdness.  Got it running just now.
